import { useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, Eye, EyeOff, Folder, Layers, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useAllsight } from "@/lib/allsight/store";
import { useT } from "@/lib/allsight/i18n";
import { cn } from "@/lib/utils";
import { ConfirmDialog, type ConfirmRequest } from "./ConfirmDialog";
import type { GalleryGroup, PersonalFolder, PropertyGroup } from "@/lib/allsight/types";

type Panel = "general" | "gallery" | "gallery-group";
const MAIN_GALLERY_ID = "__main_gallery__";

export function TagManager({ onBack }: { onBack: () => void }) {
  const t = useT();
  const store = useAllsight();
  const { state } = store;
  const general = state.propertyGroups.filter((group) => !group.id.startsWith("exclusive:") && !group.id.startsWith("gallery-group:"));
  const [panel, setPanel] = useState<Panel>("general");
  const [activeId, setActiveId] = useState(general[0]?.id ?? "");
  const [galleryId, setGalleryId] = useState<string | null>(null);
  const [galleryGroupId, setGalleryGroupId] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [galleryListOpen, setGalleryListOpen] = useState(true);
  const [galleryGroupListOpen, setGalleryGroupListOpen] = useState(true);
  const [confirmReq, setConfirmReq] = useState<ConfirmRequest | null>(null);
  const folders = useMemo(() => state.folders.filter((folder) => folder.name.toLowerCase().includes(query.toLowerCase())), [query, state.folders]);
  const active = state.propertyGroups.find((group) => group.id === activeId);
  const gallery = state.folders.find((folder) => folder.id === galleryId);
  const galleryGroup = state.galleryGroups.find((group) => group.id === galleryGroupId);

  const selectGeneral = (id: string) => { setPanel("general"); setActiveId(id); setGalleryId(null); setGalleryGroupId(null); };
  const selectGallery = (id: string) => { setPanel("gallery"); setGalleryId(id); setGalleryGroupId(null); };
  const selectGalleryGroup = (id: string) => { setPanel("gallery-group"); setGalleryGroupId(id); setGalleryId(null); };

  return <div className="flex h-screen flex-col bg-background">
    <header className="glass-panel flex items-center gap-3 rounded-none border-x-0 border-t-0 px-5 py-3">
      <button type="button" onClick={onBack} className="inline-flex items-center gap-2 rounded-lg border border-border/70 bg-secondary/50 px-3 py-1.5 text-sm font-medium hover:bg-accent"><ArrowLeft className="size-4" />{t("backToLibrary")}</button>
      <h1 className="font-display text-lg font-semibold tracking-tight">Property Management</h1>
    </header>
    <div className="flex min-h-0 flex-1">
      <nav className="app-scroll glass-panel w-64 shrink-0 space-y-3 overflow-y-auto rounded-none border-y-0 border-l-0 p-3">
        <section className="rounded-xl border border-border/65 bg-secondary/20 p-2 shadow-[inset_0_1px_rgb(255_255_255_/_0.05)]"><NavTitle label="General Property" />{general.map((group) => <NavProperty key={group.id} group={group} active={panel === "general" && activeId === group.id} onClick={() => selectGeneral(group.id)} />)}<div className="mt-2 flex items-center gap-1.5"><input id="new-general-property" placeholder="New Property Group" className="min-w-0 flex-1 rounded-lg border border-border bg-background/50 px-2.5 py-1.5 text-xs outline-none focus:ring-2 focus:ring-ring" onKeyDown={(event) => { if (event.key === "Enter" && event.currentTarget.value.trim()) { store.addPropertyGroup(event.currentTarget.value.trim()); event.currentTarget.value = ""; } }} /><button onClick={() => { const input = document.getElementById("new-general-property") as HTMLInputElement | null; if (input?.value.trim()) { store.addPropertyGroup(input.value.trim()); input.value = ""; } }} className="grid size-7 place-items-center rounded-lg border border-border/70 bg-secondary/50 hover:bg-accent"><Plus className="size-3.5" /></button></div></section>
        <section className="rounded-xl border border-border/65 bg-secondary/20 p-2 shadow-[inset_0_1px_rgb(255_255_255_/_0.05)]"><ToggleListTitle label="Gallery Group Property" open={galleryGroupListOpen} onClick={() => setGalleryGroupListOpen((open) => !open)} />{galleryGroupListOpen && <div className="mt-1 space-y-0.5">{state.galleryGroups.map((group) => <button key={group.id} onClick={() => selectGalleryGroup(group.id)} className={cn("flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm", panel === "gallery-group" && galleryGroupId === group.id ? "bg-primary/15 font-medium" : "hover:bg-accent/60")}><Layers className="size-4 text-muted-foreground" /> <span className="min-w-0 flex-1 truncate">{group.name}</span><span className="text-xs text-muted-foreground">{group.folderIds.length}</span></button>)}</div>}</section>
        <section className="rounded-xl border border-border/65 bg-secondary/20 p-2 shadow-[inset_0_1px_rgb(255_255_255_/_0.05)]"><ToggleListTitle label="Gallery Property" open={galleryListOpen} onClick={() => setGalleryListOpen((open) => !open)} />{galleryListOpen && <><SearchBox value={query} onChange={setQuery} /><div className="mt-1.5 space-y-0.5"><button onClick={() => selectGallery(MAIN_GALLERY_ID)} className={cn("flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm", panel === "gallery" && galleryId === MAIN_GALLERY_ID ? "bg-primary/15 font-medium" : "hover:bg-accent/60")}><Folder className="size-4 text-muted-foreground" /><span className="min-w-0 flex-1 truncate">Main Gallery</span></button>{folders.map((folder) => <GalleryNav key={folder.id} folder={folder} active={panel === "gallery" && galleryId === folder.id} onClick={() => selectGallery(folder.id)} />)}</div></>}</section>
      </nav>
      <main className="app-scroll min-w-0 flex-1 overflow-y-auto p-6">
        <div className="mx-auto max-w-5xl">
          {panel === "general" && active && <PropertyEditor group={active} usage={(value) => state.media.filter((media) => (media.props[active.id] ?? []).includes(value)).length} onRename={(name) => store.renamePropertyGroup(active.id, name)} onDelete={() => setConfirmReq({ title: `Remove Property Group — ${active.name}`, description: `Type the Property Group name to remove it.`, confirmText: active.name, onConfirm: () => store.deletePropertyGroup(active.id) })} onAddValue={(value) => store.createPropertyValue(active.id, value)} onRenameValue={(from, to) => store.renamePropertyValue(active.id, from, to)} onDeleteValue={(value) => store.deletePropertyValue(active.id, value)} />}
          {panel === "gallery" && galleryId === MAIN_GALLERY_ID && <MainGalleryPropertyPanel state={state} store={store} />}
          {panel === "gallery" && gallery && <GalleryPropertyPanel folder={gallery} state={state} store={store} onOpenProperty={setActiveId} />}
          {panel === "gallery-group" && galleryGroup && <GalleryGroupPropertyPanel group={galleryGroup} state={state} store={store} onOpenProperty={setActiveId} />}
          {panel === "gallery" && !gallery && galleryId !== MAIN_GALLERY_ID && <Empty text="Select a Gallery to manage its Properties." />}
          {panel === "gallery-group" && !galleryGroup && <Empty text="Select a Gallery Group to manage its Properties." />}
        </div>
      </main>
    </div>
    <ConfirmDialog request={confirmReq} onClose={() => setConfirmReq(null)} />
  </div>;
}

function NavTitle({ label }: { label: string }) { return <p className="px-2 pt-1 text-[11px] font-semibold tracking-[0.12em] text-muted-foreground uppercase">{label}</p>; }
function ToggleListTitle({ label, open, onClick }: { label: string; open: boolean; onClick: () => void }) { return <button onClick={onClick} className="flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left text-[11px] font-semibold tracking-[0.12em] text-muted-foreground uppercase hover:bg-accent/50"><ChevronDown className={cn("size-3.5 transition-transform", !open && "-rotate-90")} /><span className="flex-1">{label}</span></button>; }
function SearchBox({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="flex items-center gap-2 rounded-lg border border-border/70 bg-background/45 px-2 py-1.5"><Search className="size-3.5 text-muted-foreground" /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search Gallery" className="min-w-0 flex-1 bg-transparent text-xs outline-none" /></label>; }
function NavProperty({ group, active, onClick }: { group: PropertyGroup; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={cn("flex w-full items-center rounded-lg px-2.5 py-1.5 text-left text-sm", active ? "bg-primary/15 font-medium" : "hover:bg-accent/60")}><span className="min-w-0 flex-1 truncate">{group.name}</span><span className="text-xs text-muted-foreground">{group.values.length}</span></button>; }
function GalleryNav({ folder, active, onClick }: { folder: PersonalFolder; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={cn("flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm", active ? "bg-primary/15 font-medium" : "hover:bg-accent/60")}><Folder className="size-4 text-muted-foreground" /><span className="min-w-0 flex-1 truncate">{folder.name}</span></button>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-border text-sm text-muted-foreground">{text}</div>; }

function PropertyEditor({ group, usage, onRename, onDelete, onAddValue, onRenameValue, onDeleteValue }: { group: PropertyGroup; usage: (value: string) => number; onRename: (name: string) => void; onDelete: () => void; onAddValue: (value: string) => void; onRenameValue: (from: string, to: string) => void; onDeleteValue: (value: string) => void }) {
  const [draft, setDraft] = useState(""); const [editing, setEditing] = useState<{ value: string; draft: string } | null>(null);
  return <section className="space-y-4"><div className="flex items-center gap-2"><h2 className="font-display text-xl font-semibold">{group.name}</h2><span className="text-sm text-muted-foreground">{group.values.length} tags</span><button onClick={() => { const name = window.prompt("Rename Property Group", group.name); if (name?.trim()) onRename(name.trim()); }} className="grid size-7 place-items-center rounded-md text-muted-foreground hover:bg-accent"><Pencil className="size-3.5" /></button><button onClick={onDelete} className="grid size-7 place-items-center rounded-md text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></button></div><div className="flex max-w-md gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && draft.trim()) { onAddValue(draft.trim()); setDraft(""); } }} placeholder="New tag" className="min-w-0 flex-1 rounded-lg border border-border bg-background/50 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" /><button onClick={() => { if (draft.trim()) { onAddValue(draft.trim()); setDraft(""); } }} className="rounded-lg bg-primary/90 px-4 py-2 text-sm font-medium text-primary-foreground">Add</button></div><ul className="glass-panel divide-y divide-border/60 overflow-hidden rounded-xl">{group.values.map((value) => <li key={value} className="group flex items-center gap-3 px-4 py-2.5">{editing?.value === value ? <input autoFocus value={editing.draft} onChange={(event) => setEditing({ value, draft: event.target.value })} onBlur={() => { if (editing.draft.trim() && editing.draft !== value) onRenameValue(value, editing.draft.trim()); setEditing(null); }} onKeyDown={(event) => event.key === "Enter" && (event.target as HTMLInputElement).blur()} className="flex-1 rounded border border-border bg-background/50 px-2 py-1 text-sm" /> : <span className="flex-1 text-sm">{value}</span>}<span className="text-xs text-muted-foreground">{usage(value)}</span><button onClick={() => setEditing({ value, draft: value })} className="opacity-0 group-hover:opacity-100"><Pencil className="size-3.5" /></button><button onClick={() => onDeleteValue(value)} className="opacity-0 group-hover:opacity-100"><Trash2 className="size-3.5 text-destructive" /></button></li>)}{!group.values.length && <li className="px-4 py-6 text-center text-sm text-muted-foreground">No tags yet.</li>}</ul></section>;
}

function AccessCard({ group, disabled, onToggle }: { group: PropertyGroup; disabled: boolean; onToggle: () => void }) { return <div className={cn("flex min-w-0 items-center gap-2 rounded-xl border px-3 py-2.5", disabled ? "border-border/55 bg-secondary/20 text-muted-foreground" : "border-primary/25 bg-primary/5")}><span className="min-w-0 flex-1 truncate text-sm font-medium">{group.name}</span><button onClick={onToggle} title={disabled ? "Enable for this Gallery" : "Disable for this Gallery"} className="grid size-7 place-items-center rounded-lg hover:bg-background/60">{disabled ? <EyeOff className="size-4" /> : <Eye className="size-4 text-primary" />}</button></div>; }

function MainGalleryPropertyPanel({ state, store }: { state: ReturnType<typeof useAllsight>["state"]; store: ReturnType<typeof useAllsight> }) {
  const [draft, setDraft] = useState("");
  const [activeId, setActiveId] = useState<string | null>(null);
  const exclusive = state.propertyGroups.filter((group) => group.id.startsWith("exclusive:main:"));
  const active = exclusive.find((group) => group.id === activeId);
  return <section className="space-y-8"><div><h2 className="font-display text-2xl font-semibold">Main Gallery</h2><p className="mt-1 text-sm text-muted-foreground">Manage properties exclusive to Main Gallery.</p></div><PropertySection title="General Property" description="All system Property Groups are available in Main Gallery." groups={state.propertyGroups.filter((group) => !group.id.startsWith("exclusive:") && !group.id.startsWith("gallery-group:"))} disabled={() => false} onToggle={() => {}} /><section className="space-y-3"><div className="flex items-end justify-between gap-3"><div><h3 className="font-display text-lg font-semibold">Exclusive Gallery Property</h3><p className="text-sm text-muted-foreground">Private to Main Gallery.</p></div><div className="flex gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && draft.trim()) { store.addExclusivePropertyGroup("main", draft.trim()); setDraft(""); } }} placeholder="New Property" className="w-40 rounded-lg border border-border bg-background/50 px-2.5 py-1.5 text-sm" /><button onClick={() => { if (draft.trim()) { store.addExclusivePropertyGroup("main", draft.trim()); setDraft(""); } }} className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Plus className="size-4" /></button></div></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{exclusive.map((group) => <button key={group.id} onClick={() => setActiveId(group.id)} className={cn("rounded-xl border px-3 py-3 text-left text-sm", activeId === group.id ? "border-primary bg-primary/10" : "border-border/65 bg-secondary/20 hover:bg-accent/50")}><span className="block truncate font-medium">{group.name}</span><span className="text-xs text-muted-foreground">{group.values.length} tags</span></button>)}</div>{active && <div className="pt-2"><PropertyEditor group={active} usage={(value) => state.media.filter((media) => (media.props[active.id] ?? []).includes(value)).length} onRename={(name) => store.renamePropertyGroup(active.id, name)} onDelete={() => { store.deletePropertyGroup(active.id); setActiveId(null); }} onAddValue={(value) => store.createPropertyValue(active.id, value)} onRenameValue={(from, to) => store.renamePropertyValue(active.id, from, to)} onDeleteValue={(value) => store.deletePropertyValue(active.id, value)} /></div>}</section></section>;
}

function GalleryPropertyPanel({ folder, state, store, onOpenProperty }: { folder: PersonalFolder; state: ReturnType<typeof useAllsight>["state"]; store: ReturnType<typeof useAllsight>; onOpenProperty: (id: string) => void }) {
  const [exclusiveDraft, setExclusiveDraft] = useState(""); const [exclusiveId, setExclusiveId] = useState<string | null>(null);
  const general = state.propertyGroups.filter((group) => !group.id.startsWith("exclusive:") && !group.id.startsWith("gallery-group:"));
  const inheritedIds = state.galleryGroups.filter((group) => group.folderIds.includes(folder.id)).flatMap((group) => group.propertyGroupIds ?? []);
  const inherited = state.propertyGroups.filter((group) => inheritedIds.includes(group.id));
  const exclusive = state.propertyGroups.filter((group) => group.id.startsWith(`exclusive:${folder.id}:`));
  const exclusiveActive = exclusive.find((group) => group.id === exclusiveId);
  return <section className="space-y-8"><div><h2 className="font-display text-2xl font-semibold">{folder.name}</h2><p className="mt-1 text-sm text-muted-foreground">Property Groups this Gallery can manage.</p></div><PropertySection title="General Property" description="System Property Groups. Disabled items are unavailable in this Gallery." groups={general} disabled={(id) => (folder.disabledGeneralGroupIds ?? []).includes(id)} onToggle={(id) => store.toggleFolderProperty(folder.id, id)} />{inherited.length > 0 && <PropertySection title="Gallery Group Property" description="Inherited from every Gallery Group containing this Gallery." groups={inherited} disabled={(id) => (folder.disabledGalleryGroupIds ?? []).includes(id)} onToggle={(id) => store.toggleFolderProperty(folder.id, id)} />}<section className="space-y-3"><div className="flex items-end justify-between gap-3"><div><h3 className="font-display text-lg font-semibold">Exclusive Gallery Property</h3><p className="text-sm text-muted-foreground">Private to {folder.name}.</p></div><div className="flex gap-2"><input value={exclusiveDraft} onChange={(event) => setExclusiveDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && exclusiveDraft.trim()) { store.addExclusivePropertyGroup(folder.id, exclusiveDraft.trim()); setExclusiveDraft(""); } }} placeholder="New Property" className="w-40 rounded-lg border border-border bg-background/50 px-2.5 py-1.5 text-sm" /><button onClick={() => { if (exclusiveDraft.trim()) { store.addExclusivePropertyGroup(folder.id, exclusiveDraft.trim()); setExclusiveDraft(""); } }} className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Plus className="size-4" /></button></div></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{exclusive.map((group) => <button key={group.id} onClick={() => setExclusiveId(group.id)} className={cn("rounded-xl border px-3 py-3 text-left text-sm", exclusiveId === group.id ? "border-primary bg-primary/10" : "border-border/65 bg-secondary/20 hover:bg-accent/50")}><span className="block truncate font-medium">{group.name}</span><span className="text-xs text-muted-foreground">{group.values.length} tags</span></button>)}</div>{exclusiveActive && <div className="pt-2"><PropertyEditor group={exclusiveActive} usage={(value) => state.media.filter((media) => (media.props[exclusiveActive.id] ?? []).includes(value)).length} onRename={(name) => store.renamePropertyGroup(exclusiveActive.id, name)} onDelete={() => { store.deletePropertyGroup(exclusiveActive.id); setExclusiveId(null); }} onAddValue={(value) => store.createPropertyValue(exclusiveActive.id, value)} onRenameValue={(from, to) => store.renamePropertyValue(exclusiveActive.id, from, to)} onDeleteValue={(value) => store.deletePropertyValue(exclusiveActive.id, value)} /></div>}</section></section>;
}

function PropertySection({ title, description, groups, disabled, onToggle }: { title: string; description: string; groups: PropertyGroup[]; disabled: (id: string) => boolean; onToggle: (id: string) => void }) { return <section className="space-y-3"><div><h3 className="font-display text-lg font-semibold">{title}</h3><p className="text-sm text-muted-foreground">{description}</p></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{groups.map((group) => <AccessCard key={group.id} group={group} disabled={disabled(group.id)} onToggle={() => onToggle(group.id)} />)}{!groups.length && <p className="text-sm text-muted-foreground">No Property Groups.</p>}</div></section>; }

function GalleryGroupPropertyPanel({ group, state, store, onOpenProperty }: { group: GalleryGroup; state: ReturnType<typeof useAllsight>["state"]; store: ReturnType<typeof useAllsight>; onOpenProperty: (id: string) => void }) {
  const [draft, setDraft] = useState(""); const [activeId, setActiveId] = useState<string | null>(null);
  const properties = state.propertyGroups.filter((property) => (group.propertyGroupIds ?? []).includes(property.id));
  const active = properties.find((property) => property.id === activeId);
  const members = group.folderIds.map((id) => state.folders.find((folder) => folder.id === id)).filter(Boolean) as PersonalFolder[];
  return <section className="space-y-6"><div><h2 className="font-display text-2xl font-semibold">{group.name}</h2><p className="mt-1 text-sm text-muted-foreground">Properties here are injected into all {members.length} Galleries in this Gallery Group.</p></div><div className="flex max-w-md gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && draft.trim()) { store.addGalleryGroupProperty(group.id, draft.trim()); setDraft(""); } }} placeholder="New Gallery Group Property" className="min-w-0 flex-1 rounded-lg border border-border bg-background/50 px-3 py-2 text-sm" /><button onClick={() => { if (draft.trim()) { store.addGalleryGroupProperty(group.id, draft.trim()); setDraft(""); } }} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Add</button></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{properties.map((property) => <button key={property.id} onClick={() => setActiveId(property.id)} className={cn("rounded-xl border px-3 py-3 text-left", activeId === property.id ? "border-primary bg-primary/10" : "border-border/65 bg-secondary/20 hover:bg-accent/50")}><span className="block truncate text-sm font-medium">{property.name}</span><span className="text-xs text-muted-foreground">{property.values.length} tags</span></button>)}</div><div><h3 className="mb-2 text-sm font-semibold">Galleries in this Group</h3><div className="flex flex-wrap gap-2">{members.map((folder) => <span key={folder.id} className="rounded-lg border border-border/65 bg-secondary/30 px-3 py-2 text-sm">{folder.name}</span>)}</div></div>{active && <PropertyEditor group={active} usage={(value) => state.media.filter((media) => (media.props[active.id] ?? []).includes(value)).length} onRename={(name) => store.renamePropertyGroup(active.id, name)} onDelete={() => { store.deletePropertyGroup(active.id); setActiveId(null); }} onAddValue={(value) => store.createPropertyValue(active.id, value)} onRenameValue={(from, to) => store.renamePropertyValue(active.id, from, to)} onDeleteValue={(value) => store.deletePropertyValue(active.id, value)} />}</section>;
}
